= Technical aspects

== Technologies used

* Gradle (for building project)
* Kotlin (for production code)
* Hexagonal architecture
* Reactive programming model (with non-blocking I/O)
* Mongo for DB (although decoupled due to hexagonal architecture)

== Focused on

* Design patterns
* SOLID
* Event oriented design

== Requirements

. To have at least JVM 11 to build and run the project
. GraalVM to build native app

== Running

To build the entire app with:

[source,shell]
----
./gradlew clean build
----

To build the entire app but without running any tests:

[source,shell]
----
./gradlew clean build -x test
----

To run all tests, external dependencies (ie: DB engines) are mocked:

[source,shell]
----
./gradlew test
----

To run the entire app (in localhost) in PROD mode:

[source,shell]
----
java -jar build/quarkus-app/quarkus-run.jar
----

[NOTE]
====
Requires a running mongo database cluster. You can play with local one:

[source,shell]
----
docker run -ti --rm -p 27017:27017 mongo
----
====

Once up &amp; running you can check and interact with the REST API using http://localhost:8080/swagger-ui[swagger UI]


To run application in DEV mode:

[source,shell]
----
./gradlew quarkusDev
----

In this mode you can interact with app http://localhost:8080/q/dev[dev insights]

== Containers

You can build the container image by (make sure you build the app first `./gradlew clean build`)

[source,shell]
----
docker build -f src/main/docker/Dockerfile.jvm -t quarkus/charger-monitor-jvm .
----

A running mongo database cluster is needed, but you can play with local one:

[source,shell]
----
docker run -ti --rm -p 27017:27017 mongo
----

Then you can run the container local using:

[source,shell]
----
docker run -i --net="host" --rm -p 8080:8080 quarkus/charger-monitor-jvm
----

[NOTE]
====
Image use `mongodb://mongodb:27017` hostname, so in local you need manually resolve that IP

./etc/hosts
[source,shell]
----
127.0.0.1       mongodb
----
====

== What could be improved?

* Add support for native image
* Authorization should be used on REST endpoints to guarantee energy reports are coming from trusted sensors
* Aggregate instrumentation (ie.: _OpenTracing_) to trace complete journey of a message
* Add business metrics (ie.: with _Micrometer_)
* Use of https://github.com/lordofthejars/nosql-unit[NoSQLUnit] like framework to drive DB IT

== KNOWN errors

No known errors so far.
