openapi: 3.1.1
info:
  title: Monitor API
  description: Solar plant monitor OpenAPI
  version: "1.0.0"
  contact:
    name: Monitor Support
    url: https://www.solar.inc
    email: contact@solar.inc

servers:
  - url: http://localhost:8080/api
    description: DEV server

tags:
  - name: sensors
    description: APIs to deal with particular sensors
  - name: readings
    description: API to interact with energy readings

components:
